### ISSUE TITLE
Open sourcing helloquran.com

### ISSUE THREAD

**Issue by safizn** [t-itani/quran-in-english#1]
بارك الله فيك عمل رائع
Could you open source 'helloquran.com'/'corequran.com' and maybe open it for contributions ? I would be interested in improving it, in the future.

**Comment by t-itani** [comment]
Salam Dr. Safi,
Thank you for your request. I am a little reluctant to open these projects. Yet if you give me good enough reasons, I will surely consider it. Please share with me your thoughts regarding the improvements you have in mind.
و جزاك الله خير

**Comment by safizn** [comment]
Well opening it up for contributions is enough of a reason. Just look at projects like [Quran.com contributions](https://github.com/quran/quran.com-frontend/graphs/contributors). 
Your project has more simplistic & clear design. There are always ideas and improvements that could be implemented. I like in your project the usage of actual Arabic text (with Arabic calligraphy font) that can be copied. Not sure why you use several domains.
I personally won't contribute any time soon.
